Fix readme example spacing
The spacing in the readme is a syntax error, simple update to fix. 

``` ruby
SyntaxError: /Users/nick/src/railsapp/config/environments/development.rb:7: syntax error, unexpected ':', expecting ')'
    min_delay        : 500,    # default 1000
                     ^
/Users/nick/src/railsapp/config/environment.rb:5:in `<main>'
Tasks: TOP => db:prepare => db:load_config => environment
```